--
-- PostgreSQL database dump
--

-- Dumped from database version 11.5 (Debian 11.5-1+deb10u1)
-- Dumped by pg_dump version 12.2 (Ubuntu 12.2-4)

-- Started on 2020-08-27 14:11:33 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 8 (class 2615 OID 19007)
-- Name: ili; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA ili;


SET default_tablespace = '';

--
-- TOC entry 213 (class 1259 OID 19008)
-- Name: concepts; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.concepts (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 214 (class 1259 OID 19011)
-- Name: concepts_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.concepts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.concepts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 19013)
-- Name: models; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.models (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    version_concept_id bigint NOT NULL
);


--
-- TOC entry 216 (class 1259 OID 19016)
-- Name: models_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 19018)
-- Name: queries; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.queries (
    id bigint NOT NULL,
    query character varying(2000) NOT NULL,
    query_type_id bigint NOT NULL,
    version_concept_id bigint NOT NULL
);


--
-- TOC entry 218 (class 1259 OID 19024)
-- Name: queries_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.queries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.queries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 19026)
-- Name: queries_types; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.queries_types (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 220 (class 1259 OID 19029)
-- Name: queries_types_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.queries_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.queries_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 19031)
-- Name: versions; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.versions (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 19034)
-- Name: versions_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 19036)
-- Name: versions_x_concepts; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.versions_x_concepts (
    id bigint NOT NULL,
    url character varying(500) NOT NULL,
    concept_id bigint NOT NULL,
    version_id bigint NOT NULL
);


--
-- TOC entry 224 (class 1259 OID 19042)
-- Name: versions_x_concepts_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.versions_x_concepts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.versions_x_concepts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3134 (class 2606 OID 19045)
-- Name: concepts concepts_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.concepts
    ADD CONSTRAINT concepts_pkey PRIMARY KEY (id);


--
-- TOC entry 3136 (class 2606 OID 19047)
-- Name: models models_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.models
    ADD CONSTRAINT models_pkey PRIMARY KEY (id);


--
-- TOC entry 3138 (class 2606 OID 19049)
-- Name: queries queries_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.queries
    ADD CONSTRAINT queries_pkey PRIMARY KEY (id);


--
-- TOC entry 3140 (class 2606 OID 19051)
-- Name: queries_types queries_types_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.queries_types
    ADD CONSTRAINT queries_types_pkey PRIMARY KEY (id);


--
-- TOC entry 3142 (class 2606 OID 19053)
-- Name: versions versions_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.versions
    ADD CONSTRAINT versions_pkey PRIMARY KEY (id);


--
-- TOC entry 3144 (class 2606 OID 19055)
-- Name: versions_x_concepts versions_x_concepts_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.versions_x_concepts
    ADD CONSTRAINT versions_x_concepts_pkey PRIMARY KEY (id);


--
-- TOC entry 3148 (class 2606 OID 19056)
-- Name: versions_x_concepts fk71lnauhm6islvfr78va38nfnf; Type: FK CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.versions_x_concepts
    ADD CONSTRAINT fk71lnauhm6islvfr78va38nfnf FOREIGN KEY (version_id) REFERENCES ili.versions(id);


--
-- TOC entry 3145 (class 2606 OID 19061)
-- Name: models fk9i8qtcxsjb4ngbmpn06b0gqfa; Type: FK CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.models
    ADD CONSTRAINT fk9i8qtcxsjb4ngbmpn06b0gqfa FOREIGN KEY (version_concept_id) REFERENCES ili.versions_x_concepts(id);


--
-- TOC entry 3146 (class 2606 OID 19066)
-- Name: queries fkcf92ktrwxqk22rfh81vakk8q6; Type: FK CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.queries
    ADD CONSTRAINT fkcf92ktrwxqk22rfh81vakk8q6 FOREIGN KEY (query_type_id) REFERENCES ili.queries_types(id);


--
-- TOC entry 3149 (class 2606 OID 19071)
-- Name: versions_x_concepts fkegcsry4609xxd665ckvhyeicv; Type: FK CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.versions_x_concepts
    ADD CONSTRAINT fkegcsry4609xxd665ckvhyeicv FOREIGN KEY (concept_id) REFERENCES ili.concepts(id);


--
-- TOC entry 3147 (class 2606 OID 19076)
-- Name: queries fknk6r8srri26jd0idhryt3qtau; Type: FK CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.queries
    ADD CONSTRAINT fknk6r8srri26jd0idhryt3qtau FOREIGN KEY (version_concept_id) REFERENCES ili.versions_x_concepts(id);


-- Completed on 2020-08-27 14:11:49 -05

--
-- PostgreSQL database dump complete
--

