--
-- PostgreSQL database dump
--

-- Dumped from database version 11.5 (Debian 11.5-1+deb10u1)
-- Dumped by pg_dump version 12.2 (Ubuntu 12.2-4)

-- Started on 2020-08-27 15:07:19 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 19131)
-- Name: notifications; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA notifications;


SET default_tablespace = '';

--
-- TOC entry 233 (class 1259 OID 19132)
-- Name: notifications; Type: TABLE; Schema: notifications; Owner: -
--

CREATE TABLE notifications.notifications (
    id bigint NOT NULL,
    change_status_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    email character varying(255) NOT NULL,
    message character varying(1025) NOT NULL,
    status integer NOT NULL,
    subject character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_code bigint NOT NULL
);


--
-- TOC entry 234 (class 1259 OID 19138)
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: notifications; Owner: -
--

ALTER TABLE notifications.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME notifications.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3129 (class 2606 OID 19141)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: notifications; Owner: -
--

ALTER TABLE ONLY notifications.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


-- Completed on 2020-08-27 15:07:33 -05

--
-- PostgreSQL database dump complete
--

