spring:
  profiles:
    active: "production"

zuul:
  routes:
    microservice-ili:
      service-id: st-microservice-ili
      path: /api/ili/**
      strip-prefix: false
    microservice-administration:
      service-id: st-microservice-administration
      path: /api/administration/**
      strip-prefix: false
      sensitive-headers: 
    microservice-tasks:
      service-id: st-microservice-tasks
      path: /api/tasks/**
      strip-prefix: false
      sensitive-headers: 
    microservice-filemanager:
      service-id: st-microservice-filemanager
      path: /api/filemanager/v1/**
      strip-prefix: false
      sensitive-headers: 
    microservice-managers:
      service-id: st-microservice-managers
      path: /api/managers/**
      strip-prefix: false
      sensitive-headers: 
    microservice-operators:
      service-id: st-microservice-operators
      path: /api/operators/**
      strip-prefix: false
      sensitive-headers: 
    microservice-workspaces:
      service-id: st-microservice-workspaces
      path: /api/workspaces/**
      strip-prefix: false
      sensitive-headers: 
    microservice-providers:
      service-id: st-microservice-providers
      path: /api/providers-supplies/**
      strip-prefix: false
      sensitive-headers: 
    microservice-supplies:
      service-id: st-microservice-supplies
      path: /api/supplies/**
      strip-prefix: false
      sensitive-headers: 
    microservice-oauth:
      service-id: st-microservice-oauth
      path: /api/security/**
      sensitive-headers:
      - Cookie,
      - Set-Cookie

---
spring:
  profiles: production

eureka:
  client:
    serviceUrl:
      defaultZone: http://HOSTNAME:PORT/eureka
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 420000
            
ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 300000

server:
  port: 8091