--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2 (Debian 11.2-1.pgdg90+1)
-- Dumped by pg_dump version 12.2 (Ubuntu 12.2-4)

-- Started on 2021-05-07 10:46:11 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 20 (class 2615 OID 496072)
-- Name: providers; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA providers;


SET default_tablespace = '';

--
-- TOC entry 327 (class 1259 OID 505482)
-- Name: emitters; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.emitters (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    emitter_code bigint NOT NULL,
    emitter_type character varying(50) NOT NULL,
    request_id bigint NOT NULL
);


--
-- TOC entry 326 (class 1259 OID 505480)
-- Name: emitters_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.emitters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.emitters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 329 (class 1259 OID 505489)
-- Name: extensions; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.extensions (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    type_supply_id bigint NOT NULL
);


--
-- TOC entry 328 (class 1259 OID 505487)
-- Name: extensions_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.extensions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.extensions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 331 (class 1259 OID 505496)
-- Name: petitions; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.petitions (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    justification character varying(1000),
    manager_code bigint NOT NULL,
    observations character varying(1000) NOT NULL,
    petition_state_id bigint NOT NULL,
    provider_id bigint NOT NULL
);


--
-- TOC entry 330 (class 1259 OID 505494)
-- Name: petitions_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.petitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.petitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 333 (class 1259 OID 505506)
-- Name: petitions_states; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.petitions_states (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 332 (class 1259 OID 505504)
-- Name: petitions_states_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.petitions_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.petitions_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 335 (class 1259 OID 505513)
-- Name: provider_users; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.provider_users (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    user_code bigint NOT NULL,
    provider_id bigint NOT NULL,
    provider_profile_id bigint NOT NULL
);


--
-- TOC entry 334 (class 1259 OID 505511)
-- Name: provider_users_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.provider_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.provider_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 337 (class 1259 OID 505520)
-- Name: providers; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.providers (
    id bigint NOT NULL,
    active boolean NOT NULL,
    alias character varying(20),
    created_at timestamp without time zone NOT NULL,
    name character varying(255) NOT NULL,
    tax_identification_number character varying(255) NOT NULL,
    provider_category_id bigint NOT NULL
);


--
-- TOC entry 339 (class 1259 OID 505530)
-- Name: providers_administrators; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.providers_administrators (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    user_code bigint NOT NULL,
    provider_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- TOC entry 338 (class 1259 OID 505528)
-- Name: providers_administrators_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.providers_administrators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.providers_administrators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 341 (class 1259 OID 505537)
-- Name: providers_categorys; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.providers_categorys (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 340 (class 1259 OID 505535)
-- Name: providers_categorys_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.providers_categorys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.providers_categorys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 336 (class 1259 OID 505518)
-- Name: providers_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 343 (class 1259 OID 505544)
-- Name: providers_profiles; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.providers_profiles (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    provider_id bigint NOT NULL
);


--
-- TOC entry 342 (class 1259 OID 505542)
-- Name: providers_profiles_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.providers_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.providers_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 345 (class 1259 OID 505554)
-- Name: requests; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.requests (
    id bigint NOT NULL,
    closed_at timestamp without time zone,
    closed_by bigint,
    created_at timestamp without time zone NOT NULL,
    deadline timestamp without time zone NOT NULL,
    municipality_code character varying(10) NOT NULL,
    observations character varying(255),
    package character varying(255) NOT NULL,
    provider_id bigint NOT NULL,
    request_state_id bigint NOT NULL
);


--
-- TOC entry 344 (class 1259 OID 505552)
-- Name: requests_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 347 (class 1259 OID 505564)
-- Name: requests_states; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.requests_states (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 346 (class 1259 OID 505562)
-- Name: requests_states_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.requests_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.requests_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 349 (class 1259 OID 505571)
-- Name: roles; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 348 (class 1259 OID 505569)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 351 (class 1259 OID 505578)
-- Name: supplies_requested; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.supplies_requested (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    delivered boolean NOT NULL,
    delivered_at timestamp without time zone,
    delivered_by bigint,
    description character varying(500),
    errors character varying(1000),
    extra_file character varying(1000),
    ftp character varying(500),
    is_valid boolean,
    justification character varying(500),
    log character varying(1000),
    model_version character varying(20),
    observations character varying(500),
    url character varying(1000),
    request_id bigint NOT NULL,
    supply_requested_state_id bigint NOT NULL,
    type_supply_id bigint NOT NULL
);


--
-- TOC entry 350 (class 1259 OID 505576)
-- Name: supplies_requested_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.supplies_requested ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.supplies_requested_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 353 (class 1259 OID 505588)
-- Name: supplies_requested_states; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.supplies_requested_states (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 352 (class 1259 OID 505586)
-- Name: supplies_requested_states_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.supplies_requested_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.supplies_requested_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 355 (class 1259 OID 505595)
-- Name: supplies_revisions; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.supplies_revisions (
    id bigint NOT NULL,
    database character varying(255) NOT NULL,
    finished_at timestamp without time zone,
    finished_by bigint,
    hostname character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    port character varying(255) NOT NULL,
    schema character varying(255) NOT NULL,
    started_at timestamp without time zone NOT NULL,
    started_by bigint NOT NULL,
    username character varying(255) NOT NULL,
    supply_requested_id bigint NOT NULL
);


--
-- TOC entry 354 (class 1259 OID 505593)
-- Name: supplies_revisions_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.supplies_revisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.supplies_revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 357 (class 1259 OID 505605)
-- Name: types_supplies; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.types_supplies (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp without time zone NOT NULL,
    description character varying(255),
    metadata_required boolean NOT NULL,
    model_required boolean NOT NULL,
    name character varying(255) NOT NULL,
    provider_id bigint NOT NULL,
    provider_profile_id bigint NOT NULL
);


--
-- TOC entry 356 (class 1259 OID 505603)
-- Name: types_supplies_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.types_supplies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.types_supplies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4901 (class 2606 OID 505486)
-- Name: emitters emitters_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.emitters
    ADD CONSTRAINT emitters_pkey PRIMARY KEY (id);


--
-- TOC entry 4903 (class 2606 OID 505493)
-- Name: extensions extensions_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.extensions
    ADD CONSTRAINT extensions_pkey PRIMARY KEY (id);


--
-- TOC entry 4905 (class 2606 OID 505503)
-- Name: petitions petitions_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.petitions
    ADD CONSTRAINT petitions_pkey PRIMARY KEY (id);


--
-- TOC entry 4907 (class 2606 OID 505510)
-- Name: petitions_states petitions_states_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.petitions_states
    ADD CONSTRAINT petitions_states_pkey PRIMARY KEY (id);


--
-- TOC entry 4909 (class 2606 OID 505517)
-- Name: provider_users provider_users_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.provider_users
    ADD CONSTRAINT provider_users_pkey PRIMARY KEY (id);


--
-- TOC entry 4913 (class 2606 OID 505534)
-- Name: providers_administrators providers_administrators_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_administrators
    ADD CONSTRAINT providers_administrators_pkey PRIMARY KEY (id);


--
-- TOC entry 4915 (class 2606 OID 505541)
-- Name: providers_categorys providers_categorys_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_categorys
    ADD CONSTRAINT providers_categorys_pkey PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 505527)
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


--
-- TOC entry 4917 (class 2606 OID 505551)
-- Name: providers_profiles providers_profiles_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_profiles
    ADD CONSTRAINT providers_profiles_pkey PRIMARY KEY (id);


--
-- TOC entry 4919 (class 2606 OID 505561)
-- Name: requests requests_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.requests
    ADD CONSTRAINT requests_pkey PRIMARY KEY (id);


--
-- TOC entry 4921 (class 2606 OID 505568)
-- Name: requests_states requests_states_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.requests_states
    ADD CONSTRAINT requests_states_pkey PRIMARY KEY (id);


--
-- TOC entry 4923 (class 2606 OID 505575)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 4925 (class 2606 OID 505585)
-- Name: supplies_requested supplies_requested_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_requested
    ADD CONSTRAINT supplies_requested_pkey PRIMARY KEY (id);


--
-- TOC entry 4927 (class 2606 OID 505592)
-- Name: supplies_requested_states supplies_requested_states_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_requested_states
    ADD CONSTRAINT supplies_requested_states_pkey PRIMARY KEY (id);


--
-- TOC entry 4929 (class 2606 OID 505602)
-- Name: supplies_revisions supplies_revisions_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_revisions
    ADD CONSTRAINT supplies_revisions_pkey PRIMARY KEY (id);


--
-- TOC entry 4931 (class 2606 OID 505612)
-- Name: types_supplies types_supplies_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.types_supplies
    ADD CONSTRAINT types_supplies_pkey PRIMARY KEY (id);


--
-- TOC entry 4949 (class 2606 OID 505698)
-- Name: types_supplies fk2kah37qobcueele652mldp1s0; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.types_supplies
    ADD CONSTRAINT fk2kah37qobcueele652mldp1s0 FOREIGN KEY (provider_profile_id) REFERENCES providers.providers_profiles(id);


--
-- TOC entry 4933 (class 2606 OID 505618)
-- Name: extensions fk3phi493nkheb6gusv6xahl3wc; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.extensions
    ADD CONSTRAINT fk3phi493nkheb6gusv6xahl3wc FOREIGN KEY (type_supply_id) REFERENCES providers.types_supplies(id);


--
-- TOC entry 4939 (class 2606 OID 505648)
-- Name: providers_administrators fk4npmxi6om4uqo8crueqctg7c3; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_administrators
    ADD CONSTRAINT fk4npmxi6om4uqo8crueqctg7c3 FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


--
-- TOC entry 4948 (class 2606 OID 505693)
-- Name: types_supplies fk7eigs2yri0t5nlyfcwtba48m6; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.types_supplies
    ADD CONSTRAINT fk7eigs2yri0t5nlyfcwtba48m6 FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


--
-- TOC entry 4943 (class 2606 OID 505668)
-- Name: requests fk7qd2v6ucrur3ikrpg93keukkq; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.requests
    ADD CONSTRAINT fk7qd2v6ucrur3ikrpg93keukkq FOREIGN KEY (request_state_id) REFERENCES providers.requests_states(id);


--
-- TOC entry 4940 (class 2606 OID 505653)
-- Name: providers_administrators fk8wl0kburqyhmd7o19pkpjfyta; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_administrators
    ADD CONSTRAINT fk8wl0kburqyhmd7o19pkpjfyta FOREIGN KEY (role_id) REFERENCES providers.roles(id);


--
-- TOC entry 4947 (class 2606 OID 505688)
-- Name: supplies_revisions fk9cnls53rx5whu8iax58lxdqkh; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_revisions
    ADD CONSTRAINT fk9cnls53rx5whu8iax58lxdqkh FOREIGN KEY (supply_requested_id) REFERENCES providers.supplies_requested(id);


--
-- TOC entry 4935 (class 2606 OID 505628)
-- Name: petitions fkb22kdq9y08a67r0kq76ugwg7e; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.petitions
    ADD CONSTRAINT fkb22kdq9y08a67r0kq76ugwg7e FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


--
-- TOC entry 4936 (class 2606 OID 505633)
-- Name: provider_users fkbwxypbaus35obyyfvvtpyh38m; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.provider_users
    ADD CONSTRAINT fkbwxypbaus35obyyfvvtpyh38m FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


--
-- TOC entry 4946 (class 2606 OID 505683)
-- Name: supplies_requested fkeya9h3qxnd820lw6e8nxpv99j; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_requested
    ADD CONSTRAINT fkeya9h3qxnd820lw6e8nxpv99j FOREIGN KEY (type_supply_id) REFERENCES providers.types_supplies(id);


--
-- TOC entry 4938 (class 2606 OID 505643)
-- Name: providers fkfbgki3lhlfb59ap9n6q1fn8s; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers
    ADD CONSTRAINT fkfbgki3lhlfb59ap9n6q1fn8s FOREIGN KEY (provider_category_id) REFERENCES providers.providers_categorys(id);


--
-- TOC entry 4937 (class 2606 OID 505638)
-- Name: provider_users fkhip63a0lquv8o10uncw4k33ob; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.provider_users
    ADD CONSTRAINT fkhip63a0lquv8o10uncw4k33ob FOREIGN KEY (provider_profile_id) REFERENCES providers.providers_profiles(id);


--
-- TOC entry 4941 (class 2606 OID 505658)
-- Name: providers_profiles fkjyxjuknun276h64rbwftk78xh; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_profiles
    ADD CONSTRAINT fkjyxjuknun276h64rbwftk78xh FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


--
-- TOC entry 4944 (class 2606 OID 505673)
-- Name: supplies_requested fklmxactu5f80yek0k9vw4a2u76; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_requested
    ADD CONSTRAINT fklmxactu5f80yek0k9vw4a2u76 FOREIGN KEY (request_id) REFERENCES providers.requests(id);


--
-- TOC entry 4934 (class 2606 OID 505623)
-- Name: petitions fkp9sx4j45sx45468kj1s26f3c1; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.petitions
    ADD CONSTRAINT fkp9sx4j45sx45468kj1s26f3c1 FOREIGN KEY (petition_state_id) REFERENCES providers.petitions_states(id);


--
-- TOC entry 4945 (class 2606 OID 505678)
-- Name: supplies_requested fkpokxy510ki21ss9uk54qrdivq; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_requested
    ADD CONSTRAINT fkpokxy510ki21ss9uk54qrdivq FOREIGN KEY (supply_requested_state_id) REFERENCES providers.supplies_requested_states(id);


--
-- TOC entry 4932 (class 2606 OID 505613)
-- Name: emitters fksd916f3f9bmujkq70cmakldk9; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.emitters
    ADD CONSTRAINT fksd916f3f9bmujkq70cmakldk9 FOREIGN KEY (request_id) REFERENCES providers.requests(id);


--
-- TOC entry 4942 (class 2606 OID 505663)
-- Name: requests fksn5i4qvallc9blwf6f5ixoidf; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.requests
    ADD CONSTRAINT fksn5i4qvallc9blwf6f5ixoidf FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


-- Completed on 2021-05-07 10:46:11 -05

--
-- PostgreSQL database dump complete
--

