--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2 (Debian 11.2-1.pgdg90+1)
-- Dumped by pg_dump version 12.2 (Ubuntu 12.2-4)

-- Started on 2020-10-16 10:02:05 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 16 (class 2615 OID 20739)
-- Name: providers; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA providers;


SET default_tablespace = '';

--
-- TOC entry 376 (class 1259 OID 309881)
-- Name: emitters; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.emitters (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    emitter_code bigint NOT NULL,
    emitter_type character varying(50) NOT NULL,
    request_id bigint NOT NULL
);


--
-- TOC entry 375 (class 1259 OID 309879)
-- Name: emitters_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.emitters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.emitters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 378 (class 1259 OID 309888)
-- Name: extensions; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.extensions (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    type_supply_id bigint NOT NULL
);


--
-- TOC entry 377 (class 1259 OID 309886)
-- Name: extensions_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.extensions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.extensions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 380 (class 1259 OID 309895)
-- Name: petitions; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.petitions (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    justification character varying(1000),
    manager_code bigint NOT NULL,
    observations character varying(1000) NOT NULL,
    petition_state_id bigint NOT NULL,
    provider_id bigint NOT NULL
);


--
-- TOC entry 379 (class 1259 OID 309893)
-- Name: petitions_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.petitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.petitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 382 (class 1259 OID 309905)
-- Name: petitions_states; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.petitions_states (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 381 (class 1259 OID 309903)
-- Name: petitions_states_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.petitions_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.petitions_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 384 (class 1259 OID 309912)
-- Name: provider_users; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.provider_users (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    user_code bigint NOT NULL,
    provider_id bigint NOT NULL,
    provider_profile_id bigint NOT NULL
);


--
-- TOC entry 383 (class 1259 OID 309910)
-- Name: provider_users_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.provider_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.provider_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 386 (class 1259 OID 309919)
-- Name: providers; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.providers (
    id bigint NOT NULL,
    active boolean NOT NULL,
    alias character varying(20),
    created_at timestamp without time zone NOT NULL,
    name character varying(255) NOT NULL,
    tax_identification_number character varying(255) NOT NULL,
    provider_category_id bigint NOT NULL
);


--
-- TOC entry 388 (class 1259 OID 309929)
-- Name: providers_administrators; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.providers_administrators (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    user_code bigint NOT NULL,
    provider_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- TOC entry 387 (class 1259 OID 309927)
-- Name: providers_administrators_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.providers_administrators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.providers_administrators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 390 (class 1259 OID 309936)
-- Name: providers_categorys; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.providers_categorys (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 389 (class 1259 OID 309934)
-- Name: providers_categorys_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.providers_categorys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.providers_categorys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 385 (class 1259 OID 309917)
-- Name: providers_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 392 (class 1259 OID 309943)
-- Name: providers_profiles; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.providers_profiles (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    provider_id bigint NOT NULL
);


--
-- TOC entry 391 (class 1259 OID 309941)
-- Name: providers_profiles_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.providers_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.providers_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 394 (class 1259 OID 309953)
-- Name: requests; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.requests (
    id bigint NOT NULL,
    closed_at timestamp without time zone,
    closed_by bigint,
    created_at timestamp without time zone NOT NULL,
    deadline timestamp without time zone NOT NULL,
    municipality_code character varying(10) NOT NULL,
    observations character varying(255),
    package character varying(255) NOT NULL,
    provider_id bigint NOT NULL,
    request_state_id bigint NOT NULL
);


--
-- TOC entry 393 (class 1259 OID 309951)
-- Name: requests_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 396 (class 1259 OID 309963)
-- Name: requests_states; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.requests_states (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 395 (class 1259 OID 309961)
-- Name: requests_states_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.requests_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.requests_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 398 (class 1259 OID 309970)
-- Name: roles; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 397 (class 1259 OID 309968)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 400 (class 1259 OID 309977)
-- Name: supplies_requested; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.supplies_requested (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    delivered boolean NOT NULL,
    delivered_at timestamp without time zone,
    delivered_by bigint,
    description character varying(500),
    ftp character varying(500),
    justification character varying(500),
    model_version character varying(20),
    observations character varying(500),
    url character varying(1000),
    request_id bigint NOT NULL,
    supply_requested_state_id bigint NOT NULL,
    type_supply_id bigint NOT NULL
);


--
-- TOC entry 399 (class 1259 OID 309975)
-- Name: supplies_requested_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.supplies_requested ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.supplies_requested_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 402 (class 1259 OID 309987)
-- Name: supplies_requested_states; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.supplies_requested_states (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 401 (class 1259 OID 309985)
-- Name: supplies_requested_states_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.supplies_requested_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.supplies_requested_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 404 (class 1259 OID 309994)
-- Name: supplies_revisions; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.supplies_revisions (
    id bigint NOT NULL,
    database character varying(255) NOT NULL,
    finished_at timestamp without time zone,
    finished_by bigint,
    hostname character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    port character varying(255) NOT NULL,
    schema character varying(255) NOT NULL,
    started_at timestamp without time zone NOT NULL,
    started_by bigint NOT NULL,
    username character varying(255) NOT NULL,
    supply_requested_id bigint NOT NULL
);


--
-- TOC entry 403 (class 1259 OID 309992)
-- Name: supplies_revisions_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.supplies_revisions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.supplies_revisions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 406 (class 1259 OID 310004)
-- Name: types_supplies; Type: TABLE; Schema: providers; Owner: -
--

CREATE TABLE providers.types_supplies (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp without time zone NOT NULL,
    description character varying(255),
    metadata_required boolean NOT NULL,
    model_required boolean NOT NULL,
    name character varying(255) NOT NULL,
    provider_id bigint NOT NULL,
    provider_profile_id bigint NOT NULL
);


--
-- TOC entry 405 (class 1259 OID 310002)
-- Name: types_supplies_id_seq; Type: SEQUENCE; Schema: providers; Owner: -
--

ALTER TABLE providers.types_supplies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME providers.types_supplies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4858 (class 2606 OID 309885)
-- Name: emitters emitters_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.emitters
    ADD CONSTRAINT emitters_pkey PRIMARY KEY (id);


--
-- TOC entry 4860 (class 2606 OID 309892)
-- Name: extensions extensions_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.extensions
    ADD CONSTRAINT extensions_pkey PRIMARY KEY (id);


--
-- TOC entry 4862 (class 2606 OID 309902)
-- Name: petitions petitions_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.petitions
    ADD CONSTRAINT petitions_pkey PRIMARY KEY (id);


--
-- TOC entry 4864 (class 2606 OID 309909)
-- Name: petitions_states petitions_states_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.petitions_states
    ADD CONSTRAINT petitions_states_pkey PRIMARY KEY (id);


--
-- TOC entry 4866 (class 2606 OID 309916)
-- Name: provider_users provider_users_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.provider_users
    ADD CONSTRAINT provider_users_pkey PRIMARY KEY (id);


--
-- TOC entry 4870 (class 2606 OID 309933)
-- Name: providers_administrators providers_administrators_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_administrators
    ADD CONSTRAINT providers_administrators_pkey PRIMARY KEY (id);


--
-- TOC entry 4872 (class 2606 OID 309940)
-- Name: providers_categorys providers_categorys_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_categorys
    ADD CONSTRAINT providers_categorys_pkey PRIMARY KEY (id);


--
-- TOC entry 4868 (class 2606 OID 309926)
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


--
-- TOC entry 4874 (class 2606 OID 309950)
-- Name: providers_profiles providers_profiles_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_profiles
    ADD CONSTRAINT providers_profiles_pkey PRIMARY KEY (id);


--
-- TOC entry 4876 (class 2606 OID 309960)
-- Name: requests requests_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.requests
    ADD CONSTRAINT requests_pkey PRIMARY KEY (id);


--
-- TOC entry 4878 (class 2606 OID 309967)
-- Name: requests_states requests_states_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.requests_states
    ADD CONSTRAINT requests_states_pkey PRIMARY KEY (id);


--
-- TOC entry 4880 (class 2606 OID 309974)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 4882 (class 2606 OID 309984)
-- Name: supplies_requested supplies_requested_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_requested
    ADD CONSTRAINT supplies_requested_pkey PRIMARY KEY (id);


--
-- TOC entry 4884 (class 2606 OID 309991)
-- Name: supplies_requested_states supplies_requested_states_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_requested_states
    ADD CONSTRAINT supplies_requested_states_pkey PRIMARY KEY (id);


--
-- TOC entry 4886 (class 2606 OID 310001)
-- Name: supplies_revisions supplies_revisions_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_revisions
    ADD CONSTRAINT supplies_revisions_pkey PRIMARY KEY (id);


--
-- TOC entry 4888 (class 2606 OID 310011)
-- Name: types_supplies types_supplies_pkey; Type: CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.types_supplies
    ADD CONSTRAINT types_supplies_pkey PRIMARY KEY (id);


--
-- TOC entry 4906 (class 2606 OID 310097)
-- Name: types_supplies fk2kah37qobcueele652mldp1s0; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.types_supplies
    ADD CONSTRAINT fk2kah37qobcueele652mldp1s0 FOREIGN KEY (provider_profile_id) REFERENCES providers.providers_profiles(id);


--
-- TOC entry 4890 (class 2606 OID 310017)
-- Name: extensions fk3phi493nkheb6gusv6xahl3wc; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.extensions
    ADD CONSTRAINT fk3phi493nkheb6gusv6xahl3wc FOREIGN KEY (type_supply_id) REFERENCES providers.types_supplies(id);


--
-- TOC entry 4896 (class 2606 OID 310047)
-- Name: providers_administrators fk4npmxi6om4uqo8crueqctg7c3; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_administrators
    ADD CONSTRAINT fk4npmxi6om4uqo8crueqctg7c3 FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


--
-- TOC entry 4905 (class 2606 OID 310092)
-- Name: types_supplies fk7eigs2yri0t5nlyfcwtba48m6; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.types_supplies
    ADD CONSTRAINT fk7eigs2yri0t5nlyfcwtba48m6 FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


--
-- TOC entry 4900 (class 2606 OID 310067)
-- Name: requests fk7qd2v6ucrur3ikrpg93keukkq; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.requests
    ADD CONSTRAINT fk7qd2v6ucrur3ikrpg93keukkq FOREIGN KEY (request_state_id) REFERENCES providers.requests_states(id);


--
-- TOC entry 4897 (class 2606 OID 310052)
-- Name: providers_administrators fk8wl0kburqyhmd7o19pkpjfyta; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_administrators
    ADD CONSTRAINT fk8wl0kburqyhmd7o19pkpjfyta FOREIGN KEY (role_id) REFERENCES providers.roles(id);


--
-- TOC entry 4904 (class 2606 OID 310087)
-- Name: supplies_revisions fk9cnls53rx5whu8iax58lxdqkh; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_revisions
    ADD CONSTRAINT fk9cnls53rx5whu8iax58lxdqkh FOREIGN KEY (supply_requested_id) REFERENCES providers.supplies_requested(id);


--
-- TOC entry 4892 (class 2606 OID 310027)
-- Name: petitions fkb22kdq9y08a67r0kq76ugwg7e; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.petitions
    ADD CONSTRAINT fkb22kdq9y08a67r0kq76ugwg7e FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


--
-- TOC entry 4893 (class 2606 OID 310032)
-- Name: provider_users fkbwxypbaus35obyyfvvtpyh38m; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.provider_users
    ADD CONSTRAINT fkbwxypbaus35obyyfvvtpyh38m FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


--
-- TOC entry 4903 (class 2606 OID 310082)
-- Name: supplies_requested fkeya9h3qxnd820lw6e8nxpv99j; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_requested
    ADD CONSTRAINT fkeya9h3qxnd820lw6e8nxpv99j FOREIGN KEY (type_supply_id) REFERENCES providers.types_supplies(id);


--
-- TOC entry 4895 (class 2606 OID 310042)
-- Name: providers fkfbgki3lhlfb59ap9n6q1fn8s; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers
    ADD CONSTRAINT fkfbgki3lhlfb59ap9n6q1fn8s FOREIGN KEY (provider_category_id) REFERENCES providers.providers_categorys(id);


--
-- TOC entry 4894 (class 2606 OID 310037)
-- Name: provider_users fkhip63a0lquv8o10uncw4k33ob; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.provider_users
    ADD CONSTRAINT fkhip63a0lquv8o10uncw4k33ob FOREIGN KEY (provider_profile_id) REFERENCES providers.providers_profiles(id);


--
-- TOC entry 4898 (class 2606 OID 310057)
-- Name: providers_profiles fkjyxjuknun276h64rbwftk78xh; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.providers_profiles
    ADD CONSTRAINT fkjyxjuknun276h64rbwftk78xh FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


--
-- TOC entry 4901 (class 2606 OID 310072)
-- Name: supplies_requested fklmxactu5f80yek0k9vw4a2u76; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_requested
    ADD CONSTRAINT fklmxactu5f80yek0k9vw4a2u76 FOREIGN KEY (request_id) REFERENCES providers.requests(id);


--
-- TOC entry 4891 (class 2606 OID 310022)
-- Name: petitions fkp9sx4j45sx45468kj1s26f3c1; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.petitions
    ADD CONSTRAINT fkp9sx4j45sx45468kj1s26f3c1 FOREIGN KEY (petition_state_id) REFERENCES providers.petitions_states(id);


--
-- TOC entry 4902 (class 2606 OID 310077)
-- Name: supplies_requested fkpokxy510ki21ss9uk54qrdivq; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.supplies_requested
    ADD CONSTRAINT fkpokxy510ki21ss9uk54qrdivq FOREIGN KEY (supply_requested_state_id) REFERENCES providers.supplies_requested_states(id);


--
-- TOC entry 4889 (class 2606 OID 310012)
-- Name: emitters fksd916f3f9bmujkq70cmakldk9; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.emitters
    ADD CONSTRAINT fksd916f3f9bmujkq70cmakldk9 FOREIGN KEY (request_id) REFERENCES providers.requests(id);


--
-- TOC entry 4899 (class 2606 OID 310062)
-- Name: requests fksn5i4qvallc9blwf6f5ixoidf; Type: FK CONSTRAINT; Schema: providers; Owner: -
--

ALTER TABLE ONLY providers.requests
    ADD CONSTRAINT fksn5i4qvallc9blwf6f5ixoidf FOREIGN KEY (provider_id) REFERENCES providers.providers(id);


-- Completed on 2020-10-16 10:02:06 -05

--
-- PostgreSQL database dump complete
--
