--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2 (Debian 11.2-1.pgdg90+1)
-- Dumped by pg_dump version 12.2 (Ubuntu 12.2-4)

-- Started on 2021-05-07 10:47:18 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 22 (class 2615 OID 496074)
-- Name: tasks; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA tasks;


SET default_tablespace = '';

--
-- TOC entry 287 (class 1259 OID 496341)
-- Name: tasks; Type: TABLE; Schema: tasks; Owner: -
--

CREATE TABLE tasks.tasks (
    id bigint NOT NULL,
    closing_date timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    deadline timestamp without time zone,
    description character varying(500),
    name character varying(255) NOT NULL,
    reason character varying(500),
    task_state_id bigint NOT NULL
);


--
-- TOC entry 288 (class 1259 OID 496347)
-- Name: tasks_categories; Type: TABLE; Schema: tasks; Owner: -
--

CREATE TABLE tasks.tasks_categories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 289 (class 1259 OID 496350)
-- Name: tasks_categories_id_seq; Type: SEQUENCE; Schema: tasks; Owner: -
--

ALTER TABLE tasks.tasks_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 290 (class 1259 OID 496352)
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: tasks; Owner: -
--

ALTER TABLE tasks.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 291 (class 1259 OID 496354)
-- Name: tasks_members; Type: TABLE; Schema: tasks; Owner: -
--

CREATE TABLE tasks.tasks_members (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    member_code bigint NOT NULL,
    task_id bigint NOT NULL
);


--
-- TOC entry 292 (class 1259 OID 496357)
-- Name: tasks_members_id_seq; Type: SEQUENCE; Schema: tasks; Owner: -
--

ALTER TABLE tasks.tasks_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 293 (class 1259 OID 496359)
-- Name: tasks_metadata; Type: TABLE; Schema: tasks; Owner: -
--

CREATE TABLE tasks.tasks_metadata (
    id bigint NOT NULL,
    key character varying(255) NOT NULL,
    task_id bigint NOT NULL
);


--
-- TOC entry 294 (class 1259 OID 496362)
-- Name: tasks_metadata_id_seq; Type: SEQUENCE; Schema: tasks; Owner: -
--

ALTER TABLE tasks.tasks_metadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 295 (class 1259 OID 496364)
-- Name: tasks_metadata_properties; Type: TABLE; Schema: tasks; Owner: -
--

CREATE TABLE tasks.tasks_metadata_properties (
    id bigint NOT NULL,
    key character varying(255) NOT NULL,
    value character varying(255) NOT NULL,
    metadata_id bigint NOT NULL
);


--
-- TOC entry 296 (class 1259 OID 496370)
-- Name: tasks_metadata_properties_id_seq; Type: SEQUENCE; Schema: tasks; Owner: -
--

ALTER TABLE tasks.tasks_metadata_properties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_metadata_properties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 297 (class 1259 OID 496372)
-- Name: tasks_states; Type: TABLE; Schema: tasks; Owner: -
--

CREATE TABLE tasks.tasks_states (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 298 (class 1259 OID 496375)
-- Name: tasks_states_id_seq; Type: SEQUENCE; Schema: tasks; Owner: -
--

ALTER TABLE tasks.tasks_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 299 (class 1259 OID 496377)
-- Name: tasks_steps; Type: TABLE; Schema: tasks; Owner: -
--

CREATE TABLE tasks.tasks_steps (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    description character varying(1000) NOT NULL,
    status boolean NOT NULL,
    step_id bigint,
    task_id bigint NOT NULL,
    task_type_step_id bigint NOT NULL
);


--
-- TOC entry 300 (class 1259 OID 496383)
-- Name: tasks_steps_id_seq; Type: SEQUENCE; Schema: tasks; Owner: -
--

ALTER TABLE tasks.tasks_steps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_steps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 301 (class 1259 OID 496385)
-- Name: tasks_types_steps; Type: TABLE; Schema: tasks; Owner: -
--

CREATE TABLE tasks.tasks_types_steps (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 302 (class 1259 OID 496388)
-- Name: tasks_types_steps_id_seq; Type: SEQUENCE; Schema: tasks; Owner: -
--

ALTER TABLE tasks.tasks_types_steps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tasks.tasks_types_steps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 303 (class 1259 OID 496390)
-- Name: tasks_x_categories; Type: TABLE; Schema: tasks; Owner: -
--

CREATE TABLE tasks.tasks_x_categories (
    task_id bigint NOT NULL,
    category_id bigint NOT NULL
);


--
-- TOC entry 4896 (class 2606 OID 496543)
-- Name: tasks_categories tasks_categories_pkey; Type: CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_categories
    ADD CONSTRAINT tasks_categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4898 (class 2606 OID 496545)
-- Name: tasks_members tasks_members_pkey; Type: CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_members
    ADD CONSTRAINT tasks_members_pkey PRIMARY KEY (id);


--
-- TOC entry 4900 (class 2606 OID 496547)
-- Name: tasks_metadata tasks_metadata_pkey; Type: CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_metadata
    ADD CONSTRAINT tasks_metadata_pkey PRIMARY KEY (id);


--
-- TOC entry 4902 (class 2606 OID 496549)
-- Name: tasks_metadata_properties tasks_metadata_properties_pkey; Type: CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_metadata_properties
    ADD CONSTRAINT tasks_metadata_properties_pkey PRIMARY KEY (id);


--
-- TOC entry 4894 (class 2606 OID 496551)
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- TOC entry 4904 (class 2606 OID 496553)
-- Name: tasks_states tasks_states_pkey; Type: CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_states
    ADD CONSTRAINT tasks_states_pkey PRIMARY KEY (id);


--
-- TOC entry 4906 (class 2606 OID 496555)
-- Name: tasks_steps tasks_steps_pkey; Type: CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_steps
    ADD CONSTRAINT tasks_steps_pkey PRIMARY KEY (id);


--
-- TOC entry 4908 (class 2606 OID 496557)
-- Name: tasks_types_steps tasks_types_steps_pkey; Type: CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_types_steps
    ADD CONSTRAINT tasks_types_steps_pkey PRIMARY KEY (id);


--
-- TOC entry 4910 (class 2606 OID 496771)
-- Name: tasks_members fk2ffgbngedy5k8g9jphuemkx0i; Type: FK CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_members
    ADD CONSTRAINT fk2ffgbngedy5k8g9jphuemkx0i FOREIGN KEY (task_id) REFERENCES tasks.tasks(id);


--
-- TOC entry 4913 (class 2606 OID 496776)
-- Name: tasks_steps fk91eqoe255e72lsmpkxo6psvmx; Type: FK CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_steps
    ADD CONSTRAINT fk91eqoe255e72lsmpkxo6psvmx FOREIGN KEY (task_id) REFERENCES tasks.tasks(id);


--
-- TOC entry 4916 (class 2606 OID 496781)
-- Name: tasks_x_categories fkb4cb0gqnvfbf5ocarsrl06pub; Type: FK CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_x_categories
    ADD CONSTRAINT fkb4cb0gqnvfbf5ocarsrl06pub FOREIGN KEY (category_id) REFERENCES tasks.tasks_categories(id);


--
-- TOC entry 4911 (class 2606 OID 496786)
-- Name: tasks_metadata fki3ykfnubwe9x93mtfvbg1sdko; Type: FK CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_metadata
    ADD CONSTRAINT fki3ykfnubwe9x93mtfvbg1sdko FOREIGN KEY (task_id) REFERENCES tasks.tasks(id);


--
-- TOC entry 4914 (class 2606 OID 496791)
-- Name: tasks_steps fkmh1uts5s7p5i78ya704i9dvx3; Type: FK CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_steps
    ADD CONSTRAINT fkmh1uts5s7p5i78ya704i9dvx3 FOREIGN KEY (task_type_step_id) REFERENCES tasks.tasks_types_steps(id);


--
-- TOC entry 4915 (class 2606 OID 496796)
-- Name: tasks_steps fkmn0ex8gysk22vtt0anfy271jw; Type: FK CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_steps
    ADD CONSTRAINT fkmn0ex8gysk22vtt0anfy271jw FOREIGN KEY (step_id) REFERENCES tasks.tasks_steps(id);


--
-- TOC entry 4912 (class 2606 OID 496801)
-- Name: tasks_metadata_properties fkn41ds9u9mdvobrd8sxiw9as6p; Type: FK CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_metadata_properties
    ADD CONSTRAINT fkn41ds9u9mdvobrd8sxiw9as6p FOREIGN KEY (metadata_id) REFERENCES tasks.tasks_metadata(id);


--
-- TOC entry 4909 (class 2606 OID 496806)
-- Name: tasks fkpw2opc7ay9q1wua1kkbmwg7qc; Type: FK CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks
    ADD CONSTRAINT fkpw2opc7ay9q1wua1kkbmwg7qc FOREIGN KEY (task_state_id) REFERENCES tasks.tasks_states(id);


--
-- TOC entry 4917 (class 2606 OID 496811)
-- Name: tasks_x_categories fkrltxlgup2ma7fp2jxy26gpqvs; Type: FK CONSTRAINT; Schema: tasks; Owner: -
--

ALTER TABLE ONLY tasks.tasks_x_categories
    ADD CONSTRAINT fkrltxlgup2ma7fp2jxy26gpqvs FOREIGN KEY (task_id) REFERENCES tasks.tasks(id);


-- Completed on 2021-05-07 10:47:19 -05

--
-- PostgreSQL database dump complete
--

