--
-- PostgreSQL database dump
--

-- Dumped from database version 11.5 (Debian 11.5-1+deb10u1)
-- Dumped by pg_dump version 12.2 (Ubuntu 12.2-4)

-- Started on 2020-08-27 12:49:45 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 16 (class 2615 OID 18949)
-- Name: administration; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA administration;


SET default_tablespace = '';

--
-- TOC entry 205 (class 1259 OID 18950)
-- Name: permissions; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.permissions (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 206 (class 1259 OID 18953)
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: administration; Owner: -
--

ALTER TABLE administration.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME administration.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 18955)
-- Name: roles; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 208 (class 1259 OID 18958)
-- Name: roles_id_seq; Type: SEQUENCE; Schema: administration; Owner: -
--

ALTER TABLE administration.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME administration.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 18960)
-- Name: roles_x_permissions; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.roles_x_permissions (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL
);


--
-- TOC entry 210 (class 1259 OID 18963)
-- Name: users; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.users (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    email character varying(100) NOT NULL,
    enabled boolean NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    updated_at timestamp without time zone,
    username character varying(100) NOT NULL
);


--
-- TOC entry 211 (class 1259 OID 18969)
-- Name: users_id_seq; Type: SEQUENCE; Schema: administration; Owner: -
--

ALTER TABLE administration.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME administration.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 18971)
-- Name: users_x_roles; Type: TABLE; Schema: administration; Owner: -
--

CREATE TABLE administration.users_x_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- TOC entry 3133 (class 2606 OID 18975)
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3135 (class 2606 OID 18977)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- TOC entry 3137 (class 2606 OID 18979)
-- Name: roles_x_permissions roles_x_permissions_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.roles_x_permissions
    ADD CONSTRAINT roles_x_permissions_pkey PRIMARY KEY (role_id, permission_id);


--
-- TOC entry 3141 (class 2606 OID 18983)
-- Name: users uk_r43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.users
    ADD CONSTRAINT uk_r43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- TOC entry 3143 (class 2606 OID 18985)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3146 (class 2606 OID 18986)
-- Name: users_x_roles fk5m3oxlveydoa436r304vaaehn; Type: FK CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.users_x_roles
    ADD CONSTRAINT fk5m3oxlveydoa436r304vaaehn FOREIGN KEY (user_id) REFERENCES administration.users(id);


--
-- TOC entry 3147 (class 2606 OID 18991)
-- Name: users_x_roles fk60659q5rov7mrdxwbmkc6156y; Type: FK CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.users_x_roles
    ADD CONSTRAINT fk60659q5rov7mrdxwbmkc6156y FOREIGN KEY (role_id) REFERENCES administration.roles(id);


--
-- TOC entry 3144 (class 2606 OID 18996)
-- Name: roles_x_permissions fkdw5l2fd28ajnt9agpi3m9dw5w; Type: FK CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.roles_x_permissions
    ADD CONSTRAINT fkdw5l2fd28ajnt9agpi3m9dw5w FOREIGN KEY (role_id) REFERENCES administration.roles(id);


--
-- TOC entry 3145 (class 2606 OID 19001)
-- Name: roles_x_permissions fkphaj22xwadb0vd7vp8qcoo1rb; Type: FK CONSTRAINT; Schema: administration; Owner: -
--

ALTER TABLE ONLY administration.roles_x_permissions
    ADD CONSTRAINT fkphaj22xwadb0vd7vp8qcoo1rb FOREIGN KEY (permission_id) REFERENCES administration.permissions(id);


-- Completed on 2020-08-27 12:49:52 -05

--
-- PostgreSQL database dump complete
--

