--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2 (Debian 11.2-1.pgdg90+1)
-- Dumped by pg_dump version 12.2 (Ubuntu 12.2-4)

-- Started on 2021-05-07 10:47:44 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 23 (class 2615 OID 496075)
-- Name: workspaces; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA workspaces;


SET default_tablespace = '';

--
-- TOC entry 387 (class 1259 OID 511154)
-- Name: departments; Type: TABLE; Schema: workspaces; Owner: -
--

CREATE TABLE workspaces.departments (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 386 (class 1259 OID 511152)
-- Name: departments_id_seq; Type: SEQUENCE; Schema: workspaces; Owner: -
--

ALTER TABLE workspaces.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME workspaces.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 389 (class 1259 OID 511164)
-- Name: integrations; Type: TABLE; Schema: workspaces; Owner: -
--

CREATE TABLE workspaces.integrations (
    id bigint NOT NULL,
    database character varying(255) NOT NULL,
    errors character varying(1000),
    finished_at timestamp without time zone,
    hostname character varying(255) NOT NULL,
    manager_code bigint NOT NULL,
    password character varying(255) NOT NULL,
    port character varying(255) NOT NULL,
    schema character varying(255) NOT NULL,
    started_at timestamp without time zone NOT NULL,
    supply_ant_id bigint,
    supply_cadastre_id bigint NOT NULL,
    supply_snr_id bigint NOT NULL,
    url_map character varying(255),
    username character varying(255) NOT NULL,
    integration_state_id bigint NOT NULL,
    workspace_id bigint NOT NULL
);


--
-- TOC entry 391 (class 1259 OID 511174)
-- Name: integrations_histories; Type: TABLE; Schema: workspaces; Owner: -
--

CREATE TABLE workspaces.integrations_histories (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    manager_code bigint,
    user_code bigint,
    user_name character varying(300) NOT NULL,
    integration_id bigint NOT NULL,
    integration_state_id bigint NOT NULL
);


--
-- TOC entry 390 (class 1259 OID 511172)
-- Name: integrations_histories_id_seq; Type: SEQUENCE; Schema: workspaces; Owner: -
--

ALTER TABLE workspaces.integrations_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME workspaces.integrations_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 388 (class 1259 OID 511162)
-- Name: integrations_id_seq; Type: SEQUENCE; Schema: workspaces; Owner: -
--

ALTER TABLE workspaces.integrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME workspaces.integrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 393 (class 1259 OID 511181)
-- Name: integrations_states; Type: TABLE; Schema: workspaces; Owner: -
--

CREATE TABLE workspaces.integrations_states (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL
);


--
-- TOC entry 392 (class 1259 OID 511179)
-- Name: integrations_states_id_seq; Type: SEQUENCE; Schema: workspaces; Owner: -
--

ALTER TABLE workspaces.integrations_states ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME workspaces.integrations_states_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 395 (class 1259 OID 511191)
-- Name: integrations_stats; Type: TABLE; Schema: workspaces; Owner: -
--

CREATE TABLE workspaces.integrations_stats (
    id bigint NOT NULL,
    ant_records_number bigint,
    cadastre_records_number bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    match_number bigint NOT NULL,
    percentage double precision NOT NULL,
    snr_records_number bigint NOT NULL,
    integration_id bigint NOT NULL
);


--
-- TOC entry 394 (class 1259 OID 511189)
-- Name: integrations_stats_id_seq; Type: SEQUENCE; Schema: workspaces; Owner: -
--

ALTER TABLE workspaces.integrations_stats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME workspaces.integrations_stats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 397 (class 1259 OID 511198)
-- Name: municipalities; Type: TABLE; Schema: workspaces; Owner: -
--

CREATE TABLE workspaces.municipalities (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    department_id bigint NOT NULL
);


--
-- TOC entry 396 (class 1259 OID 511196)
-- Name: municipalities_id_seq; Type: SEQUENCE; Schema: workspaces; Owner: -
--

ALTER TABLE workspaces.municipalities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME workspaces.municipalities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 399 (class 1259 OID 511208)
-- Name: workspace_managers; Type: TABLE; Schema: workspaces; Owner: -
--

CREATE TABLE workspaces.workspace_managers (
    id bigint NOT NULL,
    manager_code bigint NOT NULL,
    observations character varying(255) NOT NULL,
    start_date date NOT NULL,
    support character varying(1000) NOT NULL,
    workspace_id bigint NOT NULL
);


--
-- TOC entry 398 (class 1259 OID 511206)
-- Name: workspace_managers_id_seq; Type: SEQUENCE; Schema: workspaces; Owner: -
--

ALTER TABLE workspaces.workspace_managers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME workspaces.workspace_managers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 401 (class 1259 OID 511218)
-- Name: workspace_operators; Type: TABLE; Schema: workspaces; Owner: -
--

CREATE TABLE workspaces.workspace_operators (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    end_date timestamp without time zone,
    manager_code bigint NOT NULL,
    number_parcels_expected bigint,
    observations character varying(255),
    operator_code bigint NOT NULL,
    start_date timestamp without time zone,
    support character varying(1000) NOT NULL,
    work_area double precision,
    workspace_id bigint NOT NULL
);


--
-- TOC entry 400 (class 1259 OID 511216)
-- Name: workspace_operators_id_seq; Type: SEQUENCE; Schema: workspaces; Owner: -
--

ALTER TABLE workspaces.workspace_operators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME workspaces.workspace_operators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 403 (class 1259 OID 511228)
-- Name: workspaces; Type: TABLE; Schema: workspaces; Owner: -
--

CREATE TABLE workspaces.workspaces (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    is_active boolean,
    updated_at timestamp without time zone,
    municipality_id bigint NOT NULL,
    workspace_id bigint
);


--
-- TOC entry 402 (class 1259 OID 511226)
-- Name: workspaces_id_seq; Type: SEQUENCE; Schema: workspaces; Owner: -
--

ALTER TABLE workspaces.workspaces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME workspaces.workspaces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4894 (class 2606 OID 511161)
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- TOC entry 4898 (class 2606 OID 511178)
-- Name: integrations_histories integrations_histories_pkey; Type: CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.integrations_histories
    ADD CONSTRAINT integrations_histories_pkey PRIMARY KEY (id);


--
-- TOC entry 4896 (class 2606 OID 511171)
-- Name: integrations integrations_pkey; Type: CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.integrations
    ADD CONSTRAINT integrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4900 (class 2606 OID 511188)
-- Name: integrations_states integrations_states_pkey; Type: CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.integrations_states
    ADD CONSTRAINT integrations_states_pkey PRIMARY KEY (id);


--
-- TOC entry 4902 (class 2606 OID 511195)
-- Name: integrations_stats integrations_stats_pkey; Type: CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.integrations_stats
    ADD CONSTRAINT integrations_stats_pkey PRIMARY KEY (id);


--
-- TOC entry 4904 (class 2606 OID 511205)
-- Name: municipalities municipalities_pkey; Type: CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.municipalities
    ADD CONSTRAINT municipalities_pkey PRIMARY KEY (id);


--
-- TOC entry 4906 (class 2606 OID 511215)
-- Name: workspace_managers workspace_managers_pkey; Type: CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.workspace_managers
    ADD CONSTRAINT workspace_managers_pkey PRIMARY KEY (id);


--
-- TOC entry 4908 (class 2606 OID 511225)
-- Name: workspace_operators workspace_operators_pkey; Type: CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.workspace_operators
    ADD CONSTRAINT workspace_operators_pkey PRIMARY KEY (id);


--
-- TOC entry 4910 (class 2606 OID 511232)
-- Name: workspaces workspaces_pkey; Type: CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.workspaces
    ADD CONSTRAINT workspaces_pkey PRIMARY KEY (id);


--
-- TOC entry 4914 (class 2606 OID 511248)
-- Name: integrations_histories fk22lcf7sk847shkiqemx9mmheo; Type: FK CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.integrations_histories
    ADD CONSTRAINT fk22lcf7sk847shkiqemx9mmheo FOREIGN KEY (integration_state_id) REFERENCES workspaces.integrations_states(id);


--
-- TOC entry 4917 (class 2606 OID 511263)
-- Name: workspace_managers fk3v94oq02hsfq0rrm0nr8rkcxx; Type: FK CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.workspace_managers
    ADD CONSTRAINT fk3v94oq02hsfq0rrm0nr8rkcxx FOREIGN KEY (workspace_id) REFERENCES workspaces.workspaces(id);


--
-- TOC entry 4911 (class 2606 OID 511233)
-- Name: integrations fk9upl96ljkw91e5kgxptp2usfw; Type: FK CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.integrations
    ADD CONSTRAINT fk9upl96ljkw91e5kgxptp2usfw FOREIGN KEY (integration_state_id) REFERENCES workspaces.integrations_states(id);


--
-- TOC entry 4920 (class 2606 OID 511278)
-- Name: workspaces fkb8odxsgj7w7odd35pdm21v9ag; Type: FK CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.workspaces
    ADD CONSTRAINT fkb8odxsgj7w7odd35pdm21v9ag FOREIGN KEY (workspace_id) REFERENCES workspaces.workspaces(id);


--
-- TOC entry 4912 (class 2606 OID 511238)
-- Name: integrations fkbrb65h3gd37lif5f9nyvrtwuv; Type: FK CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.integrations
    ADD CONSTRAINT fkbrb65h3gd37lif5f9nyvrtwuv FOREIGN KEY (workspace_id) REFERENCES workspaces.workspaces(id);


--
-- TOC entry 4916 (class 2606 OID 511258)
-- Name: municipalities fkbv7fvmtec7tpmhxb6ojlhgm6m; Type: FK CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.municipalities
    ADD CONSTRAINT fkbv7fvmtec7tpmhxb6ojlhgm6m FOREIGN KEY (department_id) REFERENCES workspaces.departments(id);


--
-- TOC entry 4915 (class 2606 OID 511253)
-- Name: integrations_stats fkfi59r439mkqwqa2aimpix6u7e; Type: FK CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.integrations_stats
    ADD CONSTRAINT fkfi59r439mkqwqa2aimpix6u7e FOREIGN KEY (integration_id) REFERENCES workspaces.integrations(id);


--
-- TOC entry 4918 (class 2606 OID 511268)
-- Name: workspace_operators fkklakxhmuhmf6ekqu4m2g2r747; Type: FK CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.workspace_operators
    ADD CONSTRAINT fkklakxhmuhmf6ekqu4m2g2r747 FOREIGN KEY (workspace_id) REFERENCES workspaces.workspaces(id);


--
-- TOC entry 4919 (class 2606 OID 511273)
-- Name: workspaces fkmo4nentxq08qcfy4uwxh7v5ud; Type: FK CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.workspaces
    ADD CONSTRAINT fkmo4nentxq08qcfy4uwxh7v5ud FOREIGN KEY (municipality_id) REFERENCES workspaces.municipalities(id);


--
-- TOC entry 4913 (class 2606 OID 511243)
-- Name: integrations_histories fktowme6te1tg8yup02jcyh38xo; Type: FK CONSTRAINT; Schema: workspaces; Owner: -
--

ALTER TABLE ONLY workspaces.integrations_histories
    ADD CONSTRAINT fktowme6te1tg8yup02jcyh38xo FOREIGN KEY (integration_id) REFERENCES workspaces.integrations(id);


-- Completed on 2021-05-07 10:47:44 -05

--
-- PostgreSQL database dump complete
--

