--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2 (Debian 11.2-1.pgdg90+1)
-- Dumped by pg_dump version 12.2 (Ubuntu 12.2-4)

-- Started on 2021-05-07 10:45:03 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 18 (class 2615 OID 496070)
-- Name: notifications; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA notifications;


SET default_tablespace = '';

--
-- TOC entry 285 (class 1259 OID 496167)
-- Name: notifications; Type: TABLE; Schema: notifications; Owner: -
--

CREATE TABLE notifications.notifications (
    id bigint NOT NULL,
    change_status_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    email character varying(255) NOT NULL,
    message character varying(1025) NOT NULL,
    status integer NOT NULL,
    subject character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_code bigint NOT NULL
);


--
-- TOC entry 286 (class 1259 OID 496173)
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: notifications; Owner: -
--

ALTER TABLE notifications.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME notifications.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4886 (class 2606 OID 496489)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: notifications; Owner: -
--

ALTER TABLE ONLY notifications.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


-- Completed on 2021-05-07 10:45:04 -05

--
-- PostgreSQL database dump complete
--

