--
-- PostgreSQL database dump
--

-- Dumped from database version 11.2 (Debian 11.2-1.pgdg90+1)
-- Dumped by pg_dump version 12.2 (Ubuntu 12.2-4)

-- Started on 2021-05-07 10:43:29 -05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 16 (class 2615 OID 496068)
-- Name: ili; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA ili;


SET default_tablespace = '';

--
-- TOC entry 305 (class 1259 OID 505217)
-- Name: concepts; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.concepts (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 304 (class 1259 OID 505215)
-- Name: concepts_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.concepts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.concepts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 307 (class 1259 OID 505224)
-- Name: models; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.models (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    version_concept_id bigint NOT NULL
);


--
-- TOC entry 306 (class 1259 OID 505222)
-- Name: models_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 309 (class 1259 OID 505231)
-- Name: queries; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.queries (
    id bigint NOT NULL,
    query character varying(2000) NOT NULL,
    query_type_id bigint NOT NULL,
    version_concept_id bigint NOT NULL
);


--
-- TOC entry 308 (class 1259 OID 505229)
-- Name: queries_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.queries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.queries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 311 (class 1259 OID 505241)
-- Name: queries_types; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.queries_types (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 310 (class 1259 OID 505239)
-- Name: queries_types_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.queries_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.queries_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 313 (class 1259 OID 505248)
-- Name: versions; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.versions (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    name character varying(255) NOT NULL
);


--
-- TOC entry 312 (class 1259 OID 505246)
-- Name: versions_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 315 (class 1259 OID 505255)
-- Name: versions_x_concepts; Type: TABLE; Schema: ili; Owner: -
--

CREATE TABLE ili.versions_x_concepts (
    id bigint NOT NULL,
    url character varying(500) NOT NULL,
    concept_id bigint NOT NULL,
    version_id bigint NOT NULL
);


--
-- TOC entry 314 (class 1259 OID 505253)
-- Name: versions_x_concepts_id_seq; Type: SEQUENCE; Schema: ili; Owner: -
--

ALTER TABLE ili.versions_x_concepts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ili.versions_x_concepts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4891 (class 2606 OID 505221)
-- Name: concepts concepts_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.concepts
    ADD CONSTRAINT concepts_pkey PRIMARY KEY (id);


--
-- TOC entry 4893 (class 2606 OID 505228)
-- Name: models models_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.models
    ADD CONSTRAINT models_pkey PRIMARY KEY (id);


--
-- TOC entry 4895 (class 2606 OID 505238)
-- Name: queries queries_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.queries
    ADD CONSTRAINT queries_pkey PRIMARY KEY (id);


--
-- TOC entry 4897 (class 2606 OID 505245)
-- Name: queries_types queries_types_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.queries_types
    ADD CONSTRAINT queries_types_pkey PRIMARY KEY (id);


--
-- TOC entry 4899 (class 2606 OID 505252)
-- Name: versions versions_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.versions
    ADD CONSTRAINT versions_pkey PRIMARY KEY (id);


--
-- TOC entry 4901 (class 2606 OID 505262)
-- Name: versions_x_concepts versions_x_concepts_pkey; Type: CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.versions_x_concepts
    ADD CONSTRAINT versions_x_concepts_pkey PRIMARY KEY (id);


--
-- TOC entry 4906 (class 2606 OID 505283)
-- Name: versions_x_concepts fk71lnauhm6islvfr78va38nfnf; Type: FK CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.versions_x_concepts
    ADD CONSTRAINT fk71lnauhm6islvfr78va38nfnf FOREIGN KEY (version_id) REFERENCES ili.versions(id);


--
-- TOC entry 4902 (class 2606 OID 505263)
-- Name: models fk9i8qtcxsjb4ngbmpn06b0gqfa; Type: FK CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.models
    ADD CONSTRAINT fk9i8qtcxsjb4ngbmpn06b0gqfa FOREIGN KEY (version_concept_id) REFERENCES ili.versions_x_concepts(id);


--
-- TOC entry 4903 (class 2606 OID 505268)
-- Name: queries fkcf92ktrwxqk22rfh81vakk8q6; Type: FK CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.queries
    ADD CONSTRAINT fkcf92ktrwxqk22rfh81vakk8q6 FOREIGN KEY (query_type_id) REFERENCES ili.queries_types(id);


--
-- TOC entry 4905 (class 2606 OID 505278)
-- Name: versions_x_concepts fkegcsry4609xxd665ckvhyeicv; Type: FK CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.versions_x_concepts
    ADD CONSTRAINT fkegcsry4609xxd665ckvhyeicv FOREIGN KEY (concept_id) REFERENCES ili.concepts(id);


--
-- TOC entry 4904 (class 2606 OID 505273)
-- Name: queries fknk6r8srri26jd0idhryt3qtau; Type: FK CONSTRAINT; Schema: ili; Owner: -
--

ALTER TABLE ONLY ili.queries
    ADD CONSTRAINT fknk6r8srri26jd0idhryt3qtau FOREIGN KEY (version_concept_id) REFERENCES ili.versions_x_concepts(id);


-- Completed on 2021-05-07 10:43:29 -05

--
-- PostgreSQL database dump complete
--

