name: CD

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html . _build"
        docs-folder: "source/"

    - name: Commit documentation changes
      run: |
        git clone https://github.com/SwissTierrasColombia/st-docs.git --branch gitpage --single-branch gitpage
        rm -r gitpage/*
        cp -r source/_build/* gitpage/
        cd gitpage
        touch .nojekyll
        git config --local user.email "agenciaimplementacion@gmail.com"
        git config --local user.name "AdminSwissTierrasColombia"
        git add .
        git commit -m "Update documentation from ST" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gitpage
        directory: gitpage
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        repository: 'SwissTierrasColombia/st-docs'
